### ISSUE TITLE
Import of `contentsmanager` submodule fails due to missing `mock` dependency on Python < 3

### ISSUE THREAD

**Issue by cfobel** [conda-forge/jupytext-feedstock#27]
# Issue

Attempting to import the `contentsmanager` submodule fails if `mock` package is not installed:

```python
>>> import jupytext.contentsmanager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\chris\mc3-x64\envs\jupytext-test\lib\site-packages\jupytext\contentsmanager.py", line 10, in <module>
    import mock
ImportError: No module named mock
```

If `jupyter notebook` is run, the resulting error is something like:

```
[C 11:49:26.180 NotebookApp] Bad config encountered during initialization:
[C 11:49:26.183 NotebookApp] The 'contents_manager_class' trait of a NotebookApp instance must be a subclass of 'notebook.services.contents.manager.ContentsManager', but a value of type 'function' (i.e. <function local_function at 0x04DC80B0>) was specified.
```

# Solution

Based on [the `install_requires` entry in the `setup.py` script of the `jupytext` package][1], the issue seems to be that the `mock` package is only required for Python versions less than 3. This means the solution for this recipe would be to:

 - remove `noarch: python`
 - use a selector to conditionally include `mock` as a requirement for Python < 3

Not sure if this is worth the effort though... I'm submitting this issue anyway in case it helps someone else that is Googling the import error.

<br/>

Environment (<code>conda list</code>):

```
$ conda list

# packages in environment at C:\Users\chris\mc3-x64\envs\jupytext-test:
#
# Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0    conda-forge
backports                 1.0                        py_2    conda-forge
certifi                   2019.9.11                py27_0    conda-forge
configparser              3.7.3                    py27_1    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
importlib_metadata        0.23                     py27_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jsonschema                3.1.1                    py27_0    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
jupytext                  1.2.4                         0    conda-forge
more-itertools            4.3.0                 py27_1000    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
pathlib2                  2.3.5                    py27_0    conda-forge
pip                       19.3.1                   py27_0    conda-forge
pyrsistent                0.15.5           py27h0c8e037_0    conda-forge
python                    2.7.15            h2880e7c_1009    conda-forge
pyyaml                    5.1.2            py27h0c8e037_0    conda-forge
scandir                   1.10.0           py27h0c8e037_0    conda-forge
setuptools                41.6.0                   py27_1    conda-forge
six                       1.13.0                   py27_0    conda-forge
traitlets                 4.3.3                    py27_0    conda-forge
vc                        9                    h7299396_1
vs2008_runtime            9.0.30729.6161                0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
wincertstore              0.2                   py27_1003    conda-forge
yaml                      0.1.7             h0c8e037_1001    conda-forge
zipp                      0.6.0                      py_0    conda-forge
```

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):

```
$ conda info

     active environment : jupytext-test
    active env location : C:\Users\chris\mc3-x64\envs\jupytext-test
            shell level : 3
       user config file : C:\Users\chris\.condarc
 populated config files : C:\Users\chris\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Users\chris\mc3-x64  (writable)
           channel URLs 👍 
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\chris\mc3-x64\pkgs
                          C:\Users\chris\.conda\pkgs
                          C:\Users\chris\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\chris\mc3-x64\envs
                          C:\Users\chris\.conda\envs
                          C:\Users\chris\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

[1]: https://github.com/mwouts/jupytext/blob/a04f54858eab7cedd53da2e01514e4778223ef16/setup.py#L38

**Comment by mwouts** [comment]
Hello @cfobel , thank you for reporting this. Well sure I'd be willing to fix this. Since you have looked into this, maybe you'd like to submit a PR with the fix? I am not a conda expert, so that would be very helpful! Thanks

**Comment by mwouts** [comment]
Well, almost one year later I learnt how to use selectors, they are pretty easy to use indeed, cf. #44
Unfortunately packages seems to be prepared only for Python 3.6 and above, so they are not of much use here... :smile: 

![Screenshot from 2020-09-02 00-57-30](https://user-images.githubusercontent.com/29915202/91914000-5d7f1000-ecb7-11ea-82ed-96f2a27b51c5.png)
